### ISSUE TITLE
[Feature Request] Variable amount of ration types

### ISSUE THREAD

**Issue by mnoreke** [JustinFreitas/ration-expiration-date#3]
I am running a survival campaign where there are more types of rations with various bonuses/durations.

It would be great if I could add/remove ration types from a growing list of rations, so it is not just limited to two of them. This could then be used for any item that is prone to spoilage, not just rations.

Module rename to "item-expiration-date" :)

**Comment by JustinFreitas** [comment]
Great idea.  Sorry that it's so limited in its current form.  It's for a game I'm in and I didn't think anyone else was actually paying attention!  lol  Lemme see what I can do for you.

**Comment by mnoreke** [comment]
I have a new crafting system I am adding for my game, that includes things like fresh carcasses that need to be butchered within so long before they go bad. So having flexibility for items (not just rations) would be super useful.

If you have questions, just reach out. :)

**Comment by JustinFreitas** [comment]
Yeah, I looked for a bit...  trying to keep it easy on myself, I think one way to provide a list would have a text field in the settings that accepts a JSON formatted string.  For any arbitrarily named property in the object, the value should be a two element array with the first being a string of the item name to check and the second an integer representing the number of days til expiration.  This would be in addition to my simple two ration settings I have already.

For example:  { "item1Prop": ["Rations, ripe.", 2], "item2Prop": ["Rations, preserved.", 365] }

I haven't tried it but that seems doable to me.  Anything else would take a lot longer for me to implement based on the ideas I was coming up with and the information that was available to accomplish those goals.

Would that be sufficient in the short term?

**Comment by mnoreke** [comment]
It could, but I think I have a fairly easy working solution based upon another module I use. 

"Beaver's Crafting System" has a popup window to configure the tools that are available, with delete and add options. Adding a days column to this method shouldn't be too difficult.

Bonus: You can utilize the ID of items instead of names.

Beavers:
https://github.com/AngryBeaver/beavers-crafting

Another item that popped into my head as I was writing this (goes hand in hand) is the ability for other modules to add items with expiration date via an API. This would allow a published adventure to "preconfigure" the suggested settings for it.

**Comment by Lertuga** [comment]
I know this is an older discussion however I have the same needs as the user mnoreke. I have a complex system with different types of foods. Being able to insert different names would be great. 
Are there any news on that front?

**Comment by JustinFreitas** [comment]
Thanks for the reminder.  I looked at it and I have a fix for where it was left long ago.  This will allow for specification of an array that supports a custom list of name/expiration-days pairs.  I'll try to get it out later today.  Here's an example... it must use this exact syntax:

[["Rations, ripe", 2], ["Rations, preserved", 365]]

![image](https://github.com/JustinFreitas/ration-expiration-date/assets/7852499/69942345-41e8-43a7-891e-275b61359db2)
