### ISSUE TITLE
[Feature Request] Integrate with Simple Calendar

### ISSUE THREAD

**Issue by ctbritt** [JustinFreitas/ration-expiration-date#5]
Rather than expire on Real World dates, have the rations expire using in-game calendar?

**Comment by JustinFreitas** [comment]
Lemme see what I can do.  Thanks for the suggestion.

**Comment by JustinFreitas** [comment]
Update to 1.2.0.  In the Settings, there is a new 'Use SimpleCalendar' checkbox.  If enabled and SimpleCalendar is installed and active in the world, it will be used.  Thanks again!

**Comment by ctbritt** [comment]
thank you!
