### ISSUE TITLE
Every item is getting an expiration date, not just rations

### ISSUE THREAD

**Issue by ctbritt** [JustinFreitas/ration-expiration-date#7]
Anything I drag to the char sheet is now getting an expiration date. 

![CleanShot 2023-07-29 at 18 52 04@2x](https://github.com/JustinFreitas/ration-expiration-date/assets/4516034/26b117fa-5626-43ef-a80c-5211b3e2d9c2)

**Comment by JustinFreitas** [comment]
What is your current date in your calendar in SimpleCalendar?

**Comment by JustinFreitas** [comment]
Oh, I misread.  Let me think about a fix.

**Comment by JustinFreitas** [comment]
I see the error in the code.  Thanks for reporting... let me test around the issue and release a new version for upgrade.

**Comment by JustinFreitas** [comment]
Ok, you are good to update to 1.2.1.  Sorry for the inconvenience and thanks for the bug report.

**Comment by ctbritt** [comment]
wow! that was fast. thank you!
